[package]
name = "bfs-kilominx-6gen-permutation-only"
version = "0.1.0"
edition = "2024"

[dependencies]
combinatorics = { path = "../../combinatorics" }
disk-based-bfs = { path = "../../disk-based-bfs" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
